name: Build

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
        shell: nix develop -c bash -e {0}

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: build
